name: create-deb-installer

on: [workflow_dispatch]

jobs:
  create-installer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: arxflay/cryptoutils-build-action@v1
        id: build-act
        with:
          os: ubuntu-latest
          build_type: Release
          build_arch: x64
          c_compiler: clang
          cpp_compiler: clang++
      - name: Create installer
        shell: bash
        run: |
          sh -c "cd '${{steps.build-act.outputs.build-dir}}' && cpack"
      - uses: actions/upload-artifact@v3
        with:
          name: deb-installer-files
          path: "${{ github.workspace }}/installers/TGZ"
